### ISSUE TITLE
Gatsby community starter submission feedback

### ISSUE THREAD

**Issue by vitaliy-at-gatsby** [maheshsamudra/gatsby-starter-prismic-blog#1]
Hi there, thank you so much for submitting your starter to be listed in Gatsby's starter library! I am one of the engineering managers at Gatsby. I have a couple of pieces of feedback for ya before we can accept the starter and list it on our page. Let us know when you've addressed them and we'll re-review the submission and get it listed on the gatsbyjs.com/starters.

1. The accessibility lighthouse score is 86 and we need all lighthouse scores to be greater than 90.
2. The documentation, particularly around getting setup in Prismic, could use more detailed instructions. What kind of type should be picked (repeatable, or single, etc) and also could be helpful to have some dummy content to insert for the user.

Thanks! Looking forward to seeing the updates.

**Comment by maheshsamudra** [comment]
Thank you for the feedback.

I've updated the code and the new lighthouse scores are as follows:
![image](https://user-images.githubusercontent.com/24204685/185479782-30f7f26f-3ccd-49b8-99fb-72f1ac08235d.png)

Also, the documentation is updated with some dummy content.

**Comment by maheshsamudra** [comment]
Hello,

Since Gatsby Cloud is no longer available, I noticed that the live demo is
not available on the theme at
https://www.gatsbyjs.com/starters/maheshsamudra/gatsby-starter-prismic-blog

Could you please update the Live demo URL to
https://gatsbystarterprismicblog.netlify.app.

Thank you.

Regards,
Mahesh Wickramasinghe.
maheshsamudra.lk
